version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:65185/api
    depends_on:
      - backend
    ports:
      - "65184:3000" # 3000 = port interne (Vite), 65184 = exposé

  backend:
    build:
      context: ./backend
    ports:
      - "65185:3001" # 3001 = port backend interne, 65185 = exposé
    env_file:
      - ./backend/.env
