version: '2.4'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "65185:3001"
    env_file:
      - ./backend/.env
    mem_limit: 128m

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://weather-back.benjamin-lecomte.com/api
    depends_on:
      - backend
    ports:
      - "65184:80"
