version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:3001/api
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/userBD.db:/app/userBD.db
